config/routes.rb
AprendiendocodigoCom::Application.routes.draw do
  resources :courses do
    resources :levels do
      resources :videos
    end
  end
  resources :categories do
    resources :courses
  end
  devise_for :users, controllers: { sessions:"sessions", registrations: "registrations"}
  root "welcome#index"
  match "/admin" => "admin#index", via: [:get]
  get "welcome/index"
  get "welcome/under_construction"
  get "welcome/index_new"
  resources :registers

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :answer,  :question, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :courses
  validates_presence_of :name
end

app/models/course.rb
class Course < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :category
  has_many :levels
  has_many :videos, through: :levels
  validates_presence_of :name, :image_url

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  belongs_to :level

  def percentage
    (levels_completed * 100)/course.levels.count
  end
end

app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :course
  has_many :videos
  has_one :quiz
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  belongs_to :quiz

  validates :question, :quiz, presence: true

  def correct_answers
    answers.where(answers: { is_correct: true })
  end

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  belongs_to :level
  has_many :questions

  validates :name, :level, presence: true
end

app/models/register.rb
class Register < ActiveRecord::Base
  validates :name, :email, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_format_of :cell_phone, with: /[0-9]+/, if: lambda { |reg| !reg.cell_phone.blank? }
  validates_uniqueness_of :email
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :level

  validates_presence_of :name, :url

  before_save :set_slug

  private
  def set_slug
    self.slug = name.parameterize
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  load_and_authorize_resource

  def index

  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)

    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: 'Register was successfully created.' }
        format.json { render action: 'show', status: :created, location: @register }
      else
        format.html { render action: 'new' }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:name, :email, :cell_phone)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
  <% if @register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% @register.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cell_phone %><br>
    <%= f.text_field :cell_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editing register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<h1>Listing registers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Cell phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= register.name %></td>
        <td><%= register.email %></td>
        <td><%= register.cell_phone %></td>
        <td><%= link_to 'Show', register %></td>
        <td><%= link_to 'Edit', edit_register_path(register) %></td>
        <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Register', new_register_path %>

app/views/registers/new.html.erb
<h1>New register</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @register.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @register.email %>
</p>

<p>
  <strong>Cell phone:</strong>
  <%= @register.cell_phone %>
</p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>